### ISSUE TITLE
ObserverModelMixins

### ISSUE THREAD

**Issue by vladimirmyshkovski** [NilCoalescing/djangochannelsrestframework#12]
Hello! Thank you for the work you did creating djangochannelsrestframework!

I want to know what are your plans for further development? I studied the code, and I have a few questions regarding Observer's.

1. ObserverModelInstanceMixin is now implemented, and looking at its code, it becomes clear what it does, but this is a little not obvious API, in my opinion.

Why not implement `CreateModelMixin`, `ListObserverModel`, `RetrieveObserverModel`, `UpdateModelMixin`, `PatchModelMixin`, `DeleteModelMixin`, which would provide more obvious functionality?

2.  Why is the delete action present in ObserverModelInstanceMixin? This may slightly confuse users of this application.

Based on what I wrote in point 1, this logic can be divided, and by inheriting mixins, the user can get everything he needs.

I will gladly take part in the development of the project, if you allow it. However, I don’t have as much experience as you do.

Where should I start?

**Comment by hishnash** [comment]
Hi @narnikgamarnikus

so the mixins here: https://github.com/hishnash/djangochannelsrestframework/blob/master/djangochannelsrestframework/mixins.py

Are intended as `actions` that can be sent to the consumer over the socket. And should be useable in cases where you do not want to have any observer logic bound in.

Observing a model means that all `save` signals from Django end up being pushed to the channel layer.  (regardless of if anyone is currently connected to the socket. One needs to do this since commonly one deploys Django over many machines so there is no method within channels to know if someone has subscribed to this model on another machine.

> Why is the delete action present in ObserverModelInstanceMixin? This may slightly confuse users of this application.

the only `actions` that are on `ObserverModelInstanceMixin` are `subscribe_instance`, `unsubscribe_instance` and `retrieve`.

`ObserverModelInstanceMixin` does, however, subscribe to all the events `create`, `update`, `delete` of the model. 

We could break `ObserverModelInstanceMixin` out so that one needs to grab different mixins to observer different events.  eg `ObserverModelCreateMixin`, ``ObserverModelDeleteMixin` etc

> I will gladly take part in the development of the project

that is great. To be honest, in the last few months I have been really busy with my other work and not had much time to get into this project :(

let me give a little roadmap here of what i think needs changing:

* fix this max length (mixed char bug) my first approach at this was very dirty need to find a better way to signify channel names but ensure they don't overlap.

* how `@observer` is bound to the model `cls` currently, this is done so that if you subclass a consumer (or mixin) it is the same observer as the other sibling subclasses of that mixin (thier is a hack for model observer but that should be made the normal way)

* #6  document (and improve API were needed) to let one observer a `filtered` list. 

* #10 channels runs a single even loop for each connection this means if you send in a msg that needs a lot of processing the consumer will wait until that has finished before reading the next message. I think it would be nice to have an option on the `@action` decorator to so that it operates fully async with respect to other incoming messages.


> Where should I start?

I'm trying to get my head around the improvements to the observer solution (will involve some metaclass magic no doubt). 

Of of the biggest holes at the moment is documentation if you have time adding some richer docs, and extending the API/etc as you do this might be super helpful.

**Comment by narnikgamarnikus** [comment]
@hishnash, Thanks for the answer.

In one of my projects, I need the ability to subscribe to a list of model instances, and I'm currently working on `ObserverModelInstancesMixin`, which is almost identical to the `ObserverModelInstanceMixin` you implemented, but instead of `retrieve` it uses `list`.

I have already written several tests, and everything works as it should, but there are some nuances. 
If I update several instances of the model, I get an exception with this traceback:

```
>       response = await communicator.receive_json_from()

tests/test_model_observer.py:570: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.7/site-packages/channels/testing/websocket.py:93: in receive_json_from
    payload = await self.receive_from(timeout)
venv/lib/python3.7/site-packages/channels/testing/websocket.py:72: in receive_from
    response = await self.receive_output(timeout)
venv/lib/python3.7/site-packages/asgiref/testing.py:86: in receive_output
    raise e
venv/lib/python3.7/site-packages/asgiref/testing.py:75: in receive_output
    return await self.output_queue.get()
venv/lib/python3.7/site-packages/async_timeout/__init__.py:55: in __aexit__
    self._do_exit(exc_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <async_timeout.timeout object at 0x7fed186fce80>, exc_type = <class 'concurrent.futures._base.CancelledError'>

    def _do_exit(self, exc_type: Type[BaseException]) -> None:
        if exc_type is asyncio.CancelledError and self._cancelled:
            self._cancel_handler = None
            self._task = None
>           raise asyncio.TimeoutError
E           concurrent.futures._base.TimeoutError

venv/lib/python3.7/site-packages/async_timeout/__init__.py:92: TimeoutError

```

Also, I had to override the `list` method, because by default, it uses a `queryset` defined in the `Consumer`, but I think it would be logical to return only those instances with which changes, and not all those returned by the default `queryset`.

**Comment by hishnash** [comment]
So to understand you don't want to send updates downstream as and when they happen but rather you want to buffer them until the client hits the `list` endpoint? 

the current `ObserverModelInstanceMixin` will send each update/change (addition/removal) of an item down the socket as a separate event.

The need for the retrieve mixin there is so that when you subscribe it can use that logic to load the item to bind the subscription.

However I do get the need for subscribing to a list of items, are you doing this by changing the channel name? used so that all the items you subscribe to fall into the same channel?

**Comment by lewis-kori** [comment]
@hishnash did you get rid of the ObserverModelMixin?
I just stumbled across your library and it's quite impressive.

would definitely want to update the docs.

**Comment by hishnash** [comment]
There is `ObserverModelInstanceMixin` to observer an instance of a model.

if you want to observer all instances (or a custom filtered list) you can use the `@model_observer` pattern. 

I have considered creating a `ObserverModelListMixin` were you can override a few methods to handle the filtering etc. If that is something your interested in i would be very interested in any ideas you might have as to how the api might be best for users?

`from djangochannelsrestframework.generics import GenericAsyncAPIConsumer`is the correct import.

 Thankyou for spotting this.

**Comment by lewis-kori** [comment]
The imports were from the https://lostmoa.com/blog/DjangoChannelsRestFrameworkSubscribingToModels/ example project.

this is what was there
`from djangochannelsrestframework.mixins import ObserverModelInstanceMixin`
and I did finally end up finding the mixin in `from djangochannelsrestframework.observer.generics import ObserverModelInstanceMixin`

> I have considered creating a ObserverModelListMixin were you can override a few methods to handle the filtering etc. If that is something your interested in i would be very interested in any ideas you might have as to how the api might be best for users?

I'll continue exploring the library and get back to you. It's definitely something I am interested in. and also help in docs.

Good job! Really appreciate your work.

**Comment by BlueOwlet** [comment]
As a new user to this I can say that learning about this project changed everything for the better regarding how we were planning on using websockets with django. Your work is much appreciated.


I also would love more detail into implementing this with channels_api, DMultiplexer and maybe some middleware too as these are some of the tooling we are working with and would love to see more examples of this in the documentation.

For example:

We have this project with the following setup:

Django for backend
vue 3
channels
channels_api
djangorestframework
djangochannelsrestframework
djoser

Initially all requests where from within django templates but we ended up having to use Django decoupled with Vue 3 for frontend due to the heavy requirements from frontend team

The authentication scheme changed to token based and we settled on using djoser library to help implement the token authentication. As soon as we did this we realized that even though user was connecting with token to the websocket it was showing as undefined in self.scope['user']. We ended up implementing some basic middleware to authenticate user. Are there any plans to improve the security out of the box for multiple types of authentication?




consumers.py

```

class Groups_Consumer(
        ListModelMixin,
        # RetrieveModelMixin, #these are commented out because included in ObserverModelInstance
        # PatchModelMixin,
        # UpdateModelMixin,
        # CreateModelMixin,
        DeleteModelMixin,
        ObserverModelInstanceMixin,
        GenericAsyncAPIConsumer):

    permission_classes = (permissions.IsAuthenticated,)

    queryset=Group.objects.all()
    serializer_class=GroupSerializer


    @action()
    async def subscribe_to_groups_feed(self, request_id, **kwargs):
        await self.groups_feed.subscribe(request_id=request_id)

    @model_observer(Group,serializer_class=GroupSerializer)
    async def groups_feed(self, data, action, subscribing_request_ids=[], **kwargs):
        for request_id in subscribing_request_ids:
            await self.reply(data=data, action=action, request_id=request_id)

```


And then I want to subscribe to a filtered list; according to documentation I could do something like this.

```

    @model_observer(Attendance)
    async def attendance_activity(self,message: AttendanceSerializer,observer=None,action=None,subscribing_request_ids=[],**kwargs):
        for request_id in subscribing_request_ids:
        # we can send a seperate message for each subscribing request
        # this lets ws clients rout these messages.
            print('SUB 3')
            await self.send_json(dict(body=message, action=action, request_id=request_id))

    @attendance_activity.serializer
    def attendance_activity(self, instance: Attendance, action, **kwargs) -> AttendanceSerializer:
        '''This will return the comment serializer'''

        return AttendanceSerializer(instance)

    @attendance_activity.groups_for_signal
    def attendance_activity(self, instance: Attendance, **kwargs):
        # this block of code is called very often *DO NOT make DB QUERIES HERE*

        yield f'-attendance__{instance}'  #! the string **user** is the ``Comment's`` user field.

    @attendance_activity.groups_for_consumer
    def attendance_activity(self, school=None, classroom=None, **kwargs):
        # This is called when you subscribe/unsubscribe
        print('SUB 2')

        yield f'-user__{self.scope["user"].pk}'

    @action()
    async def subscribe_to_attendance_activity(self, request_id, **kwargs):

        # We will check if the user is authenticated for subscribing.
        if "user" in self.scope and self.scope["user"].is_authenticated:
            print('SUB 1')
            await self.attendance_activity.subscribe(request_id=request_id)
```

After trying to implement this for a good week on the actual project it hasn't worked once u.u
Is there really a need for so much setup for 1 filtered queryset? Am I doing it wrong? 

When I then make javascript requests I'll end up with something like this:

```

    let data={
      stream:'groups',
      payload:{
        action:'subscribe_to_attendance_activity',
        pk:attendance.pk,
        request_id:new Date().getTime()
      }
    }

    ws.send(JSON.stringify(data))


```

And so... usually for regular actions like 'list', 'create','delete' and subscribing to the main queryset, which is usually a '.all()' queryset, it works great; but when trying to subscribe to a Filtered List it doesn't really work as expected. Is there a place I can read more about this?
